@FoodApp.Api_HostAddress = http://192.168.254.100:5114/api

### GET
GET {{FoodApp.Api_HostAddress}}/ProductCategories/1/products

### GET
GET {{FoodApp.Api_HostAddress}}/ProductCategories
Accept: application/json

### POST request to create a new product
POST {{FoodApp.Api_HostAddress}}/products/
Content-Type: application/json

{
  "name": "Sample Product",
  "categoryId": 1,
  "price":  100.0,
  "stock": 50
}


### POST request to create a new product
POST {{FoodApp.Api_HostAddress}}/orders/
Content-Type: application/json

{
  "order" : {
    "customerName": "test customer name",
    "isPaid" : true,
    "orderItems": [
      {
        "productId": 1,
        "quantity": 2,
        "price": 10.99
      },
      {
        "productId": 2,
        "quantity": 1,
        "price": 5.49
      }
    ]
  }
}

### GET
GET {{FoodApp.Api_HostAddress}}/orders?pageNumber=1&pageSize=10
Accept: application/json
